### ISSUE TITLE
Hello! Project Creation, Prof. Issa's invited, and Alondra's Status. 

### ISSUE THREAD

**Issue by JKBRUIN** [fffade/MoffatBay#1]
Hello, Jeremiah K. here. 
And create a project page in 'Projects' following the instructions in Assignment 1 since you're admin so we can start working on things. 
Please invite Joseph Issa as a collaborator: 
jissa@bellevue.edu 

Have you heard back from Alondra?

**Comment by fffade** [comment]
Done.

No response from Alondra yet, though.
