### ISSUE TITLE
Create landing page HTML/CSS

### ISSUE THREAD

**Issue by fffade** [fffade/MoffatBay#10]
We need to develop a landing page (index.html) for the site.

This page is static and has no backend code.

Our landing page should utilize an include for the header.

**Comment by fffade** [comment]
Landing page is complete at **index.jsp**.

Please review.

**Comment by JKBRUIN** [comment]
corrected NavBar address from reservations.jsp to reserve.jsp to link the BOOK button correctly to reservation form. Please verify if that was needed or was intended for something else.

**Comment by JKBRUIN** [comment]
Landing page wants me to go on vacation.  Screens now scale correctly. And we can scroll.  Awesome work.
