### ISSUE TITLE
Create reservation page HTML/CSS

### ISSUE THREAD

**Issue by fffade** [fffade/MoffatBay#15]
Create a reservation form for logged in users.

It should utilize the included header.

**Comment by fffade** [comment]
Reservation page just needs room recommendations filled out.

**Comment by JKBRUIN** [comment]
Tried using page.  Doesn't get a scroll bar if bigger than window.  Looking to see if it's an issue for all pages.

**Comment by fffade** [comment]
Room recommendations filled out.
