### ISSUE TITLE
Write SQL files for populating the database tables

### ISSUE THREAD

**Issue by fffade** [fffade/MoffatBay#8]
We must write SQL code to insert a few sample entries into our two tables: Accounts and Reservations.

**Comment by fffade** [comment]
**Accounts**
(1, "John", "Doe", "johndoe21@gmail.com", "6147008910", "jd7000!!")
(2, "Marcus", "Walker", "mwalker2001@gmail.com", "6149826464", "ILuvWaffles4@")
(3, "Lucy", "Alexander", "lucymusic@outlook.com", "7408114300", "Musicals20$$")

**Reservations**
(1, 1, "KG", 1, 115.0, "2024-06-05", "2024-06-06")
(2, 2, "2FB", 3, 300.0, "2024-07-15", "2024-07-17")
(3, 3, "QU", 2, 345.0, "2024-08-21", "2024-08-24")

**Comment by JKBRUIN** [comment]
I'll get cracking on these today and tomorrow

**Comment by JKBRUIN** [comment]
I'm repushing back to main for this. 
Populate.jsp was only a copy of CreateTable.jsp
